<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/cluster/v1/message.proto

namespace Temporal\Api\Cluster\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.cluster.v1.ClusterMember</code>
 */
class ClusterMember extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.ClusterMemberRole role = 1;</code>
     */
    protected $role = 0;
    /**
     * Generated from protobuf field <code>string host_id = 2;</code>
     */
    protected $host_id = '';
    /**
     * Generated from protobuf field <code>string rpc_address = 3;</code>
     */
    protected $rpc_address = '';
    /**
     * Generated from protobuf field <code>int32 rpc_port = 4;</code>
     */
    protected $rpc_port = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp session_start_time = 5 [(.gogoproto.stdtime) = true];</code>
     */
    protected $session_start_time = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_heartbit_time = 6 [(.gogoproto.stdtime) = true];</code>
     */
    protected $last_heartbit_time = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp record_expiry_time = 7 [(.gogoproto.stdtime) = true];</code>
     */
    protected $record_expiry_time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $role
     *     @type string $host_id
     *     @type string $rpc_address
     *     @type int $rpc_port
     *     @type \Google\Protobuf\Timestamp $session_start_time
     *     @type \Google\Protobuf\Timestamp $last_heartbit_time
     *     @type \Google\Protobuf\Timestamp $record_expiry_time
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Cluster\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.ClusterMemberRole role = 1;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.ClusterMemberRole role = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\ClusterMemberRole::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string host_id = 2;</code>
     * @return string
     */
    public function getHostId()
    {
        return $this->host_id;
    }

    /**
     * Generated from protobuf field <code>string host_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHostId($var)
    {
        GPBUtil::checkString($var, True);
        $this->host_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rpc_address = 3;</code>
     * @return string
     */
    public function getRpcAddress()
    {
        return $this->rpc_address;
    }

    /**
     * Generated from protobuf field <code>string rpc_address = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRpcAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->rpc_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rpc_port = 4;</code>
     * @return int
     */
    public function getRpcPort()
    {
        return $this->rpc_port;
    }

    /**
     * Generated from protobuf field <code>int32 rpc_port = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRpcPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->rpc_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp session_start_time = 5 [(.gogoproto.stdtime) = true];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getSessionStartTime()
    {
        return $this->session_start_time;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp session_start_time = 5 [(.gogoproto.stdtime) = true];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setSessionStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->session_start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_heartbit_time = 6 [(.gogoproto.stdtime) = true];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getLastHeartbitTime()
    {
        return $this->last_heartbit_time;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_heartbit_time = 6 [(.gogoproto.stdtime) = true];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastHeartbitTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_heartbit_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp record_expiry_time = 7 [(.gogoproto.stdtime) = true];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getRecordExpiryTime()
    {
        return $this->record_expiry_time;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp record_expiry_time = 7 [(.gogoproto.stdtime) = true];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setRecordExpiryTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->record_expiry_time = $var;

        return $this;
    }

}

