<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/cluster/v1/message.proto

namespace Temporal\Api\Cluster\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.cluster.v1.IndexSearchAttributes</code>
 */
class IndexSearchAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .temporal.api.enums.v1.IndexedValueType> custom_search_attributes = 1;</code>
     */
    private $custom_search_attributes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $custom_search_attributes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Cluster\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .temporal.api.enums.v1.IndexedValueType> custom_search_attributes = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCustomSearchAttributes()
    {
        return $this->custom_search_attributes;
    }

    /**
     * Generated from protobuf field <code>map<string, .temporal.api.enums.v1.IndexedValueType> custom_search_attributes = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCustomSearchAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::ENUM, \Temporal\Api\Enums\V1\IndexedValueType::class);
        $this->custom_search_attributes = $arr;

        return $this;
    }

}

