<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/cluster/v1/message.proto

namespace Temporal\Api\Cluster\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.cluster.v1.MembershipInfo</code>
 */
class MembershipInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.temporal.api.cluster.v1.HostInfo current_host = 1;</code>
     */
    protected $current_host = null;
    /**
     * Generated from protobuf field <code>repeated string reachable_members = 2;</code>
     */
    private $reachable_members;
    /**
     * Generated from protobuf field <code>repeated .temporal.api.cluster.v1.RingInfo rings = 3;</code>
     */
    private $rings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Temporal\Api\Cluster\V1\HostInfo $current_host
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $reachable_members
     *     @type \Temporal\Api\Cluster\V1\RingInfo[]|\Google\Protobuf\Internal\RepeatedField $rings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Cluster\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.cluster.v1.HostInfo current_host = 1;</code>
     * @return \Temporal\Api\Cluster\V1\HostInfo
     */
    public function getCurrentHost()
    {
        return $this->current_host;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.cluster.v1.HostInfo current_host = 1;</code>
     * @param \Temporal\Api\Cluster\V1\HostInfo $var
     * @return $this
     */
    public function setCurrentHost($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Cluster\V1\HostInfo::class);
        $this->current_host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string reachable_members = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReachableMembers()
    {
        return $this->reachable_members;
    }

    /**
     * Generated from protobuf field <code>repeated string reachable_members = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReachableMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->reachable_members = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .temporal.api.cluster.v1.RingInfo rings = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRings()
    {
        return $this->rings;
    }

    /**
     * Generated from protobuf field <code>repeated .temporal.api.cluster.v1.RingInfo rings = 3;</code>
     * @param \Temporal\Api\Cluster\V1\RingInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Cluster\V1\RingInfo::class);
        $this->rings = $arr;

        return $this;
    }

}

