<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/cluster/v1/message.proto

namespace Temporal\Api\Cluster\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.cluster.v1.RingInfo</code>
 */
class RingInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string role = 1;</code>
     */
    protected $role = '';
    /**
     * Generated from protobuf field <code>int32 member_count = 2;</code>
     */
    protected $member_count = 0;
    /**
     * Generated from protobuf field <code>repeated .temporal.api.cluster.v1.HostInfo members = 3;</code>
     */
    private $members;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $role
     *     @type int $member_count
     *     @type \Temporal\Api\Cluster\V1\HostInfo[]|\Google\Protobuf\Internal\RepeatedField $members
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Cluster\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string role = 1;</code>
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>string role = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 member_count = 2;</code>
     * @return int
     */
    public function getMemberCount()
    {
        return $this->member_count;
    }

    /**
     * Generated from protobuf field <code>int32 member_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->member_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .temporal.api.cluster.v1.HostInfo members = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * Generated from protobuf field <code>repeated .temporal.api.cluster.v1.HostInfo members = 3;</code>
     * @param \Temporal\Api\Cluster\V1\HostInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Cluster\V1\HostInfo::class);
        $this->members = $arr;

        return $this;
    }

}

