<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/enums/v1/reset.proto

namespace GPBMetadata\Temporal\Api\Enums\V1;

class Reset
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab6020a2174656d706f72616c2f6170692f656e756d732f76312f72657365742e70726f746f121574656d706f72616c2e6170692e656e756d732e76312a720a10526573657452656170706c795479706512220a1e52455345545f52454150504c595f545950455f554e5350454349464945441000121d0a1952455345545f52454150504c595f545950455f5349474e414c1001121b0a1752455345545f52454150504c595f545950455f4e4f4e451002427e0a18696f2e74656d706f72616c2e6170692e656e756d732e7631420a526573657450726f746f50015a21676f2e74656d706f72616c2e696f2f6170692f656e756d732f76313b656e756d73aa021554656d706f72616c2e4170692e456e756d732e5631ea021854656d706f72616c3a3a4170693a3a456e756d733a3a5631620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

