<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/operatorservice/v1/request_response.proto

namespace Temporal\Api\Operatorservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.operatorservice.v1.DescribeClusterResponse</code>
 */
class DescribeClusterResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, string> supported_clients = 1;</code>
     */
    private $supported_clients;
    /**
     * Generated from protobuf field <code>string server_version = 2;</code>
     */
    protected $server_version = '';
    /**
     * Generated from protobuf field <code>.temporal.api.cluster.v1.MembershipInfo membership_info = 3;</code>
     */
    protected $membership_info = null;
    /**
     * Generated from protobuf field <code>string cluster_id = 4;</code>
     */
    protected $cluster_id = '';
    /**
     * Generated from protobuf field <code>string cluster_name = 5;</code>
     */
    protected $cluster_name = '';
    /**
     * Generated from protobuf field <code>int32 history_shard_count = 6;</code>
     */
    protected $history_shard_count = 0;
    /**
     * Generated from protobuf field <code>string persistence_store = 7;</code>
     */
    protected $persistence_store = '';
    /**
     * Generated from protobuf field <code>string visibility_store = 8;</code>
     */
    protected $visibility_store = '';
    /**
     * Generated from protobuf field <code>.temporal.api.version.v1.VersionInfo version_info = 9;</code>
     */
    protected $version_info = null;
    /**
     * Generated from protobuf field <code>int64 failover_version_increment = 10;</code>
     */
    protected $failover_version_increment = 0;
    /**
     * Generated from protobuf field <code>int64 initial_failover_version = 11;</code>
     */
    protected $initial_failover_version = 0;
    /**
     * Generated from protobuf field <code>bool is_global_namespace_enabled = 12;</code>
     */
    protected $is_global_namespace_enabled = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $supported_clients
     *     @type string $server_version
     *     @type \Temporal\Api\Cluster\V1\MembershipInfo $membership_info
     *     @type string $cluster_id
     *     @type string $cluster_name
     *     @type int $history_shard_count
     *     @type string $persistence_store
     *     @type string $visibility_store
     *     @type \Temporal\Api\Version\V1\VersionInfo $version_info
     *     @type int|string $failover_version_increment
     *     @type int|string $initial_failover_version
     *     @type bool $is_global_namespace_enabled
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Operatorservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, string> supported_clients = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSupportedClients()
    {
        return $this->supported_clients;
    }

    /**
     * Generated from protobuf field <code>map<string, string> supported_clients = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSupportedClients($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->supported_clients = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string server_version = 2;</code>
     * @return string
     */
    public function getServerVersion()
    {
        return $this->server_version;
    }

    /**
     * Generated from protobuf field <code>string server_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServerVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->server_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.cluster.v1.MembershipInfo membership_info = 3;</code>
     * @return \Temporal\Api\Cluster\V1\MembershipInfo
     */
    public function getMembershipInfo()
    {
        return $this->membership_info;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.cluster.v1.MembershipInfo membership_info = 3;</code>
     * @param \Temporal\Api\Cluster\V1\MembershipInfo $var
     * @return $this
     */
    public function setMembershipInfo($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Cluster\V1\MembershipInfo::class);
        $this->membership_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cluster_id = 4;</code>
     * @return string
     */
    public function getClusterId()
    {
        return $this->cluster_id;
    }

    /**
     * Generated from protobuf field <code>string cluster_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setClusterId($var)
    {
        GPBUtil::checkString($var, True);
        $this->cluster_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cluster_name = 5;</code>
     * @return string
     */
    public function getClusterName()
    {
        return $this->cluster_name;
    }

    /**
     * Generated from protobuf field <code>string cluster_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setClusterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->cluster_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 history_shard_count = 6;</code>
     * @return int
     */
    public function getHistoryShardCount()
    {
        return $this->history_shard_count;
    }

    /**
     * Generated from protobuf field <code>int32 history_shard_count = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setHistoryShardCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->history_shard_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string persistence_store = 7;</code>
     * @return string
     */
    public function getPersistenceStore()
    {
        return $this->persistence_store;
    }

    /**
     * Generated from protobuf field <code>string persistence_store = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPersistenceStore($var)
    {
        GPBUtil::checkString($var, True);
        $this->persistence_store = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string visibility_store = 8;</code>
     * @return string
     */
    public function getVisibilityStore()
    {
        return $this->visibility_store;
    }

    /**
     * Generated from protobuf field <code>string visibility_store = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setVisibilityStore($var)
    {
        GPBUtil::checkString($var, True);
        $this->visibility_store = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.version.v1.VersionInfo version_info = 9;</code>
     * @return \Temporal\Api\Version\V1\VersionInfo
     */
    public function getVersionInfo()
    {
        return $this->version_info;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.version.v1.VersionInfo version_info = 9;</code>
     * @param \Temporal\Api\Version\V1\VersionInfo $var
     * @return $this
     */
    public function setVersionInfo($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Version\V1\VersionInfo::class);
        $this->version_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 failover_version_increment = 10;</code>
     * @return int|string
     */
    public function getFailoverVersionIncrement()
    {
        return $this->failover_version_increment;
    }

    /**
     * Generated from protobuf field <code>int64 failover_version_increment = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFailoverVersionIncrement($var)
    {
        GPBUtil::checkInt64($var);
        $this->failover_version_increment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 initial_failover_version = 11;</code>
     * @return int|string
     */
    public function getInitialFailoverVersion()
    {
        return $this->initial_failover_version;
    }

    /**
     * Generated from protobuf field <code>int64 initial_failover_version = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInitialFailoverVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->initial_failover_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_global_namespace_enabled = 12;</code>
     * @return bool
     */
    public function getIsGlobalNamespaceEnabled()
    {
        return $this->is_global_namespace_enabled;
    }

    /**
     * Generated from protobuf field <code>bool is_global_namespace_enabled = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsGlobalNamespaceEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->is_global_namespace_enabled = $var;

        return $this;
    }

}

