<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/operatorservice/v1/request_response.proto

namespace Temporal\Api\Operatorservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.operatorservice.v1.ListClusterMembersRequest</code>
 */
class ListClusterMembersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * (-- api-linter: core::0140::prepositions=disabled
     *     aip.dev/not-precedent: "within" is used to indicate a time range. --)
     *
     * Generated from protobuf field <code>.google.protobuf.Duration last_heartbeat_within = 1 [(.gogoproto.stdduration) = true];</code>
     */
    protected $last_heartbeat_within = null;
    /**
     * Generated from protobuf field <code>string rpc_address = 2;</code>
     */
    protected $rpc_address = '';
    /**
     * Generated from protobuf field <code>string host_id = 3;</code>
     */
    protected $host_id = '';
    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.ClusterMemberRole role = 4;</code>
     */
    protected $role = 0;
    /**
     * (-- api-linter: core::0140::prepositions=disabled
     *     aip.dev/not-precedent: "after" is used to indicate a time range. --)
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp session_started_after_time = 5 [(.gogoproto.stdtime) = true];</code>
     */
    protected $session_started_after_time = null;
    /**
     * Generated from protobuf field <code>int32 page_size = 6;</code>
     */
    protected $page_size = 0;
    /**
     * Generated from protobuf field <code>bytes next_page_token = 7;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Duration $last_heartbeat_within
     *           (-- api-linter: core::0140::prepositions=disabled
     *               aip.dev/not-precedent: "within" is used to indicate a time range. --)
     *     @type string $rpc_address
     *     @type string $host_id
     *     @type int $role
     *     @type \Google\Protobuf\Timestamp $session_started_after_time
     *           (-- api-linter: core::0140::prepositions=disabled
     *               aip.dev/not-precedent: "after" is used to indicate a time range. --)
     *     @type int $page_size
     *     @type string $next_page_token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Operatorservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * (-- api-linter: core::0140::prepositions=disabled
     *     aip.dev/not-precedent: "within" is used to indicate a time range. --)
     *
     * Generated from protobuf field <code>.google.protobuf.Duration last_heartbeat_within = 1 [(.gogoproto.stdduration) = true];</code>
     * @return \Google\Protobuf\Duration
     */
    public function getLastHeartbeatWithin()
    {
        return $this->last_heartbeat_within;
    }

    /**
     * (-- api-linter: core::0140::prepositions=disabled
     *     aip.dev/not-precedent: "within" is used to indicate a time range. --)
     *
     * Generated from protobuf field <code>.google.protobuf.Duration last_heartbeat_within = 1 [(.gogoproto.stdduration) = true];</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setLastHeartbeatWithin($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->last_heartbeat_within = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rpc_address = 2;</code>
     * @return string
     */
    public function getRpcAddress()
    {
        return $this->rpc_address;
    }

    /**
     * Generated from protobuf field <code>string rpc_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRpcAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->rpc_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string host_id = 3;</code>
     * @return string
     */
    public function getHostId()
    {
        return $this->host_id;
    }

    /**
     * Generated from protobuf field <code>string host_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHostId($var)
    {
        GPBUtil::checkString($var, True);
        $this->host_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.ClusterMemberRole role = 4;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.ClusterMemberRole role = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\ClusterMemberRole::class);
        $this->role = $var;

        return $this;
    }

    /**
     * (-- api-linter: core::0140::prepositions=disabled
     *     aip.dev/not-precedent: "after" is used to indicate a time range. --)
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp session_started_after_time = 5 [(.gogoproto.stdtime) = true];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getSessionStartedAfterTime()
    {
        return $this->session_started_after_time;
    }

    /**
     * (-- api-linter: core::0140::prepositions=disabled
     *     aip.dev/not-precedent: "after" is used to indicate a time range. --)
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp session_started_after_time = 5 [(.gogoproto.stdtime) = true];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setSessionStartedAfterTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->session_started_after_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 6;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes next_page_token = 7;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Generated from protobuf field <code>bytes next_page_token = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->next_page_token = $var;

        return $this;
    }

}

